version: 2

api:
  exchange: CoinEx

trading:
  pairs: ["BTCUSDT", "ETHUSDT", "LTCUSDT", "SOLUSDT", "BNBUSDT"]
  default_interval: "5m"
  max_positions: 2
  dry_run: true
  threshold: 0.1
  fee: 0.0004
  default_capital: 10
  min_size: 0.0001
  backtest_lookback: 500

risk:
  per_trade: 0.01
  stop_loss_pct: 0.005
  take_profit_pct: 0.01
  trailing_stop_pct: 0.008
  max_drawdown_pct: 0.15
  max_daily_loss_pct: 0.05

ml:
  enabled: true
  min_signal_conf: 0.5
  retrain_on_start: false

strategy:
  mode: normal
  autotune: true

notifications:
  telegram_bot_token: ""
  telegram_chat_id: ""
  webhook_url: ""

debug: false
log_level: "INFO"